# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-02-17 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeSys', models.CharField(max_length=200)),
                ('TimeSec', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PcbAdc', models.IntegerField(default=0)),
                ('TempAdc', models.IntegerField(default=0)),
                ('HCurrent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Res2Adc', models.IntegerField(default=0)),
                ('Res1Adc', models.IntegerField(default=0)),
                ('PcbTemp', models.DecimalField(decimal_places=4, max_digits=6)),
                ('SnsrTemp', models.DecimalField(decimal_places=4, max_digits=6)),
                ('Messages', models.CharField(max_length=200)),
                ('line_number', models.IntegerField(default=0)),
                ('file_name', models.CharField(max_length=200)),
                ('config', models.CharField(max_length=200)),
                ('sensor_number', models.CharField(max_length=200)),
            ],
        ),
    ]
