# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-02-17 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='SnsrTemp',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
    ]
