# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-02-18 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_auto_20160217_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor2Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeSys', models.CharField(max_length=200)),
                ('TimeSec', models.DecimalField(decimal_places=2, max_digits=9)),
                ('PcbTemp', models.IntegerField(default=0)),
                ('SnsrTemp', models.DecimalField(decimal_places=5, max_digits=8)),
                ('HCurrent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Res1Adc', models.IntegerField(default=0)),
                ('AdjRes1', models.IntegerField(default=0)),
                ('ResZero', models.IntegerField(default=0)),
                ('Percentage_H2_Res', models.DecimalField(decimal_places=4, max_digits=5)),
                ('Percentage_H2', models.DecimalField(decimal_places=5, max_digits=6)),
                ('Messages', models.CharField(max_length=200)),
                ('line_number', models.IntegerField(default=0)),
                ('file_name', models.CharField(max_length=200)),
                ('config', models.CharField(max_length=200)),
                ('sensor_number', models.CharField(max_length=200)),
                ('Sensor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.Sensor2')),
            ],
        ),
    ]
